import type { SkillSlug, StepIconKey } from "@/lib/skills";

export type SubSkillStatus = "done" | "running" | "queued";

export type SubSkillStat = {
  label: string;
  value: string;
  spark: number[];
  deltaPct?: number;
};

export type SubSkill = {
  id: string;
  parent: SkillSlug;
  name: string;
  description: string;
  iconKey: StepIconKey;
  stats: [SubSkillStat, SubSkillStat];
  worklist: { id: string; label: string; status: SubSkillStatus }[];
};

const sk = (
  parent: SkillSlug,
  id: string,
  name: string,
  description: string,
  iconKey: StepIconKey,
  stats: [SubSkillStat, SubSkillStat],
  worklist: { id: string; label: string; status: SubSkillStatus }[],
): SubSkill => ({ parent, id, name, description, iconKey, stats, worklist });

export const subSkills: SubSkill[] = [
  // ───────────────────────────── KYC ─────────────────────────────
  sk("kyc", "identity-check", "Identity check",
    "Verify a customer's documents and selfie against the issuer of record.",
    "fingerprint",
    [
      { label: "Cases this month", value: "12,840", spark: [62, 70, 65, 78, 82, 88, 92], deltaPct: 14 },
      { label: "Match confidence", value: "97.2%", spark: [94, 95, 95, 96, 96, 97, 97], deltaPct: 1.4 },
    ],
    [
      { id: "1", label: "Lopez, Maria — passport + selfie", status: "done" },
      { id: "2", label: "Tanaka, Hiro — driver's license", status: "done" },
      { id: "3", label: "Okafor, Ada — national ID", status: "done" },
      { id: "4", label: "Brown, J. — passport (low-confidence selfie)", status: "running" },
      { id: "5", label: "Müller, Anna — residence permit", status: "running" },
      { id: "6", label: "Patel, Rohan — passport", status: "queued" },
      { id: "7", label: "Silva, Carla — driver's license", status: "queued" },
    ],
  ),
  sk("kyc", "watchlist-match", "Watchlist match",
    "Screen a customer against sanctions and politically exposed person lists.",
    "radar",
    [
      { label: "Screens today", value: "4,210", spark: [40, 42, 50, 48, 55, 60, 64], deltaPct: 9 },
      { label: "True hits", value: "0.31%", spark: [0.5, 0.42, 0.39, 0.36, 0.34, 0.33, 0.31], deltaPct: -3 },
    ],
    [
      { id: "1", label: "Acme Holdings GmbH — sanctions clear", status: "done" },
      { id: "2", label: "K. Petrov — possible match · adjudicating", status: "running" },
      { id: "3", label: "L. Garcia — clear", status: "done" },
      { id: "4", label: "Bay Trading LLP — clear", status: "done" },
      { id: "5", label: "M. Al-Hassan — escalated to analyst", status: "running" },
      { id: "6", label: "T. Nguyen — queued", status: "queued" },
    ],
  ),
  sk("kyc", "ownership-trace", "Beneficial-ownership trace",
    "Walk the corporate structure to find every individual with ≥ 25% ownership.",
    "layers",
    [
      { label: "Entities mapped", value: "1,430", spark: [22, 28, 35, 41, 50, 58, 67], deltaPct: 22 },
      { label: "Avg trace depth", value: "3.4 hops", spark: [3.0, 3.1, 3.2, 3.3, 3.3, 3.4, 3.4] },
    ],
    [
      { id: "1", label: "Northwind Capital — 6 owners traced", status: "done" },
      { id: "2", label: "Helios Trading — circular ownership flagged", status: "running" },
      { id: "3", label: "Apex Logistics SA — 4 owners traced", status: "done" },
      { id: "4", label: "Riverbend Holdings — partial · awaiting registry", status: "running" },
      { id: "5", label: "Cobalt Maritime — queued", status: "queued" },
    ],
  ),
  sk("kyc", "risk-score", "Customer-risk score",
    "Combine identity, geography, and watchlist signals into a tiered risk score.",
    "scale",
    [
      { label: "Avg score", value: "Low–Med", spark: [42, 41, 43, 44, 42, 41, 41] },
      { label: "High-risk rate", value: "2.4%", spark: [3.1, 2.9, 2.7, 2.6, 2.5, 2.5, 2.4], deltaPct: -8 },
    ],
    [
      { id: "1", label: "Walker, S. — Low", status: "done" },
      { id: "2", label: "Aboagye, K. — Medium", status: "done" },
      { id: "3", label: "Chen, W. — High · escalated", status: "running" },
      { id: "4", label: "Zaitsev, V. — Medium", status: "done" },
      { id: "5", label: "Halim, R. — pending source-of-funds", status: "queued" },
      { id: "6", label: "Ngata, P. — Low", status: "done" },
    ],
  ),
  sk("kyc", "suspicious-activity", "Suspicious-activity report",
    "Draft and file a suspicious-activity report with the relevant regulator.",
    "gavel",
    [
      { label: "Reports drafted", value: "228", spark: [28, 30, 33, 35, 36, 38, 40], deltaPct: 7 },
      { label: "Avg drafting time", value: "11 min", spark: [38, 30, 24, 18, 14, 12, 11], deltaPct: -71 },
    ],
    [
      { id: "1", label: "Case 7F2A1C — drafted, ready for analyst", status: "done" },
      { id: "2", label: "Case 91D44B — gathering transaction context", status: "running" },
      { id: "3", label: "Case 5C0FE2 — filed FinCEN", status: "done" },
      { id: "4", label: "Case 22A7B9 — queued", status: "queued" },
    ],
  ),
  sk("kyc", "periodic-review", "Periodic re-review",
    "Re-screen and re-document existing customers on the policy-defined cadence.",
    "calendar",
    [
      { label: "Files refreshed", value: "8,920", spark: [200, 280, 340, 410, 460, 520, 590], deltaPct: 12 },
      { label: "Overdue", value: "0.8%", spark: [3.2, 2.8, 2.1, 1.6, 1.2, 1.0, 0.8], deltaPct: -75 },
    ],
    [
      { id: "1", label: "Q1 cohort A — 412 of 412 complete", status: "done" },
      { id: "2", label: "Q1 cohort B — 287 of 320 in progress", status: "running" },
      { id: "3", label: "Q2 cohort A — scheduled May 4", status: "queued" },
      { id: "4", label: "VIP cohort — annual refresh due", status: "queued" },
    ],
  ),
  sk("kyc", "adverse-media", "Adverse-media scan",
    "Search news and public records for negative coverage of a customer.",
    "radar",
    [
      { label: "Customers scanned", value: "5,640", spark: [60, 64, 68, 72, 78, 82, 90], deltaPct: 11 },
      { label: "Hits per 1k", value: "3.1", spark: [4.4, 4.0, 3.6, 3.4, 3.2, 3.1, 3.1] },
    ],
    [
      { id: "1", label: "Northwind Capital — 1 article · low relevance", status: "done" },
      { id: "2", label: "T. Reyes — 3 articles · escalated", status: "running" },
      { id: "3", label: "Helios Trading — clear", status: "done" },
      { id: "4", label: "Riverbend Holdings — pending review", status: "queued" },
    ],
  ),
  sk("kyc", "doc-reverify", "Document re-verification",
    "Re-check expiring documents and request fresh copies before expiry.",
    "verified",
    [
      { label: "Docs re-verified", value: "3,470", spark: [30, 33, 38, 42, 46, 50, 56], deltaPct: 14 },
      { label: "Customers contacted", value: "1,280", spark: [12, 14, 16, 18, 20, 21, 23] },
    ],
    [
      { id: "1", label: "Walker, S. — passport renewed", status: "done" },
      { id: "2", label: "Tanaka, H. — license expiring in 30d", status: "running" },
      { id: "3", label: "Garcia, L. — request sent", status: "running" },
      { id: "4", label: "Müller, A. — queued", status: "queued" },
    ],
  ),
  sk("kyc", "address-verify", "Address verification",
    "Confirm a customer's address against utility bills and postal records.",
    "shield",
    [
      { label: "Addresses verified", value: "9,210", spark: [80, 86, 92, 100, 108, 116, 122], deltaPct: 8 },
      { label: "Mismatch rate", value: "1.4%", spark: [2.8, 2.4, 2.0, 1.8, 1.6, 1.5, 1.4], deltaPct: -50 },
    ],
    [
      { id: "1", label: "12 Maple St — confirmed", status: "done" },
      { id: "2", label: "8 Rue Lafayette — utility bill received", status: "done" },
      { id: "3", label: "204 Park Ave — mismatch · contacting customer", status: "running" },
      { id: "4", label: "44 Oak Ln — queued", status: "queued" },
    ],
  ),
  sk("kyc", "source-of-funds", "Source-of-funds review",
    "Document and verify where a customer's money is coming from.",
    "archive",
    [
      { label: "Reviews this month", value: "612", spark: [50, 56, 62, 68, 74, 78, 82], deltaPct: 16 },
      { label: "Avg review time", value: "32 min", spark: [110, 90, 72, 55, 44, 38, 32], deltaPct: -71 },
    ],
    [
      { id: "1", label: "Apex Logistics SA — payroll + escrow verified", status: "done" },
      { id: "2", label: "T. Reyes — bank statements pending", status: "running" },
      { id: "3", label: "Cobalt Maritime — questionnaire sent", status: "queued" },
    ],
  ),
  sk("kyc", "deeper-review", "Onboarding deeper review",
    "Run extra checks on customers who score high-risk at onboarding.",
    "shield",
    [
      { label: "Cases entered", value: "188", spark: [16, 18, 20, 24, 26, 28, 30] },
      { label: "Approve rate", value: "78%", spark: [70, 72, 74, 75, 76, 77, 78] },
    ],
    [
      { id: "1", label: "Helios Trading — ownership trace + media", status: "running" },
      { id: "2", label: "T. Reyes — analyst interview scheduled", status: "queued" },
      { id: "3", label: "Apex Logistics SA — approved with conditions", status: "done" },
    ],
  ),
  sk("kyc", "annual-refresh", "Annual file refresh",
    "Refresh every existing customer's file once per year, end-to-end.",
    "calendar",
    [
      { label: "Files refreshed YTD", value: "62,400", spark: [3000, 6500, 11000, 18000, 28000, 44000, 62400], deltaPct: 18 },
      { label: "On-time rate", value: "99.2%", spark: [96, 97, 98, 98, 99, 99, 99] },
    ],
    [
      { id: "1", label: "Tier 1 — 12,400 of 12,400 complete", status: "done" },
      { id: "2", label: "Tier 2 — 38,200 of 40,000 in progress", status: "running" },
      { id: "3", label: "Tier 3 — scheduled Q3", status: "queued" },
    ],
  ),

  // ───────────────────────────── Finance ─────────────────────────────
  sk("finance", "payroll", "Payroll",
    "Run payroll cycles across employees, contractors, and entities.",
    "send",
    [
      { label: "Runs this month", value: "382", spark: [42, 46, 52, 58, 64, 70, 76], deltaPct: 9 },
      { label: "Total paid", value: "$5.1M", spark: [600, 620, 700, 740, 800, 860, 920], deltaPct: 11 },
    ],
    [
      { id: "1", label: "US bi-weekly — 1,140 employees", status: "done" },
      { id: "2", label: "UK monthly — 320 employees", status: "running" },
      { id: "3", label: "EU contractors — 84 invoices", status: "running" },
      { id: "4", label: "APAC monthly — scheduled May 1", status: "queued" },
    ],
  ),
  sk("finance", "invoice-approval", "Invoice approval",
    "Route incoming invoices through the right approval chain.",
    "check",
    [
      { label: "Invoices routed", value: "2,840", spark: [200, 230, 260, 290, 320, 360, 400], deltaPct: 16 },
      { label: "Avg cycle", value: "1.6 days", spark: [4.2, 3.6, 3.0, 2.4, 2.0, 1.8, 1.6], deltaPct: -62 },
    ],
    [
      { id: "1", label: "Datadog Nov — auto-approved", status: "done" },
      { id: "2", label: "AWS Nov — controller review", status: "running" },
      { id: "3", label: "Snowflake Q4 — VP approval pending", status: "running" },
      { id: "4", label: "Notion seat add-on — auto-approved", status: "done" },
      { id: "5", label: "Cloudflare overage — queued", status: "queued" },
    ],
  ),
  sk("finance", "expense-reimb", "Expense reimbursement",
    "Categorize, approve, and pay back employee expenses.",
    "receipt",
    [
      { label: "Reports processed", value: "1,920", spark: [150, 170, 190, 210, 230, 250, 280] },
      { label: "Avg pay-back time", value: "2.1 days", spark: [6.0, 5.0, 4.2, 3.4, 2.8, 2.4, 2.1], deltaPct: -65 },
    ],
    [
      { id: "1", label: "K. Lin — travel · approved", status: "done" },
      { id: "2", label: "S. Patel — client dinner · auto-approved", status: "done" },
      { id: "3", label: "M. Diaz — laptop accessory · policy review", status: "running" },
      { id: "4", label: "J. Kim — conference · queued", status: "queued" },
    ],
  ),
  sk("finance", "vendor-onboarding", "Vendor onboarding",
    "Stand up a new vendor with tax forms, banking details, and contract on file.",
    "briefcase",
    [
      { label: "Vendors onboarded", value: "146", spark: [10, 12, 14, 16, 18, 22, 24] },
      { label: "Avg setup time", value: "3.2 days", spark: [9.0, 7.4, 6.0, 4.8, 4.0, 3.6, 3.2], deltaPct: -64 },
    ],
    [
      { id: "1", label: "Acme Studios — tax forms verified", status: "done" },
      { id: "2", label: "Helios Trading — banking pending", status: "running" },
      { id: "3", label: "Northwind Capital — contract review", status: "running" },
      { id: "4", label: "Bay Trading LLP — queued", status: "queued" },
    ],
  ),
  sk("finance", "month-end-close", "Month-end close",
    "Close the books at month-end with a live progress dashboard.",
    "scale",
    [
      { label: "Days to close", value: "2.0", spark: [10, 8, 6, 4, 3, 2.4, 2.0], deltaPct: -80 },
      { label: "Reclasses", value: "0.4%", spark: [6.0, 4.4, 3.0, 2.0, 1.2, 0.8, 0.4], deltaPct: -93 },
    ],
    [
      { id: "1", label: "Bank reconciliations — 12 of 12", status: "done" },
      { id: "2", label: "Accruals — drafted", status: "done" },
      { id: "3", label: "Revenue cut-off review — running", status: "running" },
      { id: "4", label: "Intercompany eliminations — running", status: "running" },
      { id: "5", label: "FX revaluation — queued", status: "queued" },
    ],
  ),
  sk("finance", "bank-recon", "Bank reconciliation",
    "Match bank-feed transactions against the ledger and flag exceptions.",
    "scale",
    [
      { label: "Transactions matched", value: "118,400", spark: [9000, 10000, 11500, 13000, 15000, 17500, 20000] },
      { label: "Match rate", value: "99.6%", spark: [97.2, 98.0, 98.6, 99.0, 99.3, 99.5, 99.6] },
    ],
    [
      { id: "1", label: "Bank of America #4421 — reconciled", status: "done" },
      { id: "2", label: "Chase #1882 — 4 unmatched · investigating", status: "running" },
      { id: "3", label: "HSBC UK #6020 — reconciled", status: "done" },
      { id: "4", label: "Mizuho JP #0114 — queued", status: "queued" },
    ],
  ),
  sk("finance", "tax-filing", "Tax filing prep",
    "Prepare quarterly and annual tax filings with line-item evidence.",
    "archive",
    [
      { label: "Filings drafted", value: "84", spark: [8, 9, 10, 11, 12, 13, 14] },
      { label: "On-time rate", value: "100%", spark: [98, 99, 100, 100, 100, 100, 100] },
    ],
    [
      { id: "1", label: "Q1 sales-tax — drafted across 18 states", status: "done" },
      { id: "2", label: "VAT EU — 8 jurisdictions in progress", status: "running" },
      { id: "3", label: "Federal estimated — queued", status: "queued" },
    ],
  ),
  sk("finance", "ar-chase", "Accounts receivable chase",
    "Politely chase customers for overdue invoices, with the right cadence.",
    "send",
    [
      { label: "Days sales outstanding", value: "32", spark: [48, 44, 40, 38, 36, 34, 32], deltaPct: -33 },
      { label: "Outreach sent", value: "1,260", spark: [80, 100, 120, 140, 160, 180, 200] },
    ],
    [
      { id: "1", label: "Inv 5821 — Acme Studios — paid", status: "done" },
      { id: "2", label: "Inv 5904 — Helios Trading — 2nd reminder sent", status: "running" },
      { id: "3", label: "Inv 6011 — Bay Trading — escalated to AM", status: "running" },
      { id: "4", label: "Inv 6122 — Northwind — first reminder queued", status: "queued" },
    ],
  ),
  sk("finance", "ap-run", "Accounts payable run",
    "Pay vendors on schedule, optimizing early-pay discounts.",
    "send",
    [
      { label: "Payments scheduled", value: "942", spark: [80, 88, 96, 104, 112, 120, 128] },
      { label: "Discount captured", value: "$214K", spark: [10, 14, 18, 22, 26, 30, 34], deltaPct: 28 },
    ],
    [
      { id: "1", label: "Bi-weekly run — 412 vendors", status: "done" },
      { id: "2", label: "Early-pay discount run — 38 vendors", status: "running" },
      { id: "3", label: "International wire batch — 24 vendors", status: "queued" },
    ],
  ),
  sk("finance", "budget-variance", "Budget variance review",
    "Spot meaningful gaps between budget and actuals, then route them for review.",
    "scale",
    [
      { label: "Lines reviewed", value: "3,860", spark: [300, 340, 380, 420, 460, 500, 540] },
      { label: "Material variances", value: "11", spark: [22, 18, 16, 14, 13, 12, 11], deltaPct: -50 },
    ],
    [
      { id: "1", label: "Cloud infra — 14% over budget · explained", status: "done" },
      { id: "2", label: "Marketing — 22% under · awaiting comment", status: "running" },
      { id: "3", label: "Travel — 8% over · acceptable", status: "done" },
      { id: "4", label: "Legal — variance review queued", status: "queued" },
    ],
  ),
  sk("finance", "audit-pull", "Audit pull",
    "Assemble an audit-ready evidence package on demand.",
    "archive",
    [
      { label: "Pulls completed", value: "32", spark: [3, 4, 5, 6, 7, 8, 10] },
      { label: "Avg assembly time", value: "18 min", spark: [240, 180, 120, 90, 60, 30, 18], deltaPct: -92 },
    ],
    [
      { id: "1", label: "Q4 revenue sample · 200 invoices", status: "done" },
      { id: "2", label: "FX hedging trades · evidence package", status: "running" },
      { id: "3", label: "Stock-comp roll-forward — queued", status: "queued" },
    ],
  ),
  sk("finance", "fixed-assets", "Fixed-asset register",
    "Track every fixed asset from acquisition to disposal, with depreciation.",
    "database",
    [
      { label: "Assets tracked", value: "12,400", spark: [8000, 8800, 9600, 10400, 11200, 11800, 12400], deltaPct: 6 },
      { label: "Depreciation posted", value: "$1.84M", spark: [220, 240, 260, 280, 300, 320, 340] },
    ],
    [
      { id: "1", label: "Q1 depreciation run — posted", status: "done" },
      { id: "2", label: "Laptop refresh program — 412 assets added", status: "done" },
      { id: "3", label: "Lease vs buy review — running", status: "running" },
      { id: "4", label: "Year-end disposal review — queued", status: "queued" },
    ],
  ),

  // ───────────────────────────── HR ─────────────────────────────
  sk("hr", "new-hire", "New-hire onboarding",
    "Get a new hire from offer-accepted to fully productive on day one.",
    "briefcase",
    [
      { label: "Hires onboarded", value: "412", spark: [40, 46, 52, 58, 64, 70, 76], deltaPct: 12 },
      { label: "Day-1 ready rate", value: "98.6%", spark: [88, 92, 94, 96, 97, 98, 99] },
    ],
    [
      { id: "1", label: "K. Otieno — engineer · day-1 ready", status: "done" },
      { id: "2", label: "M. Strauss — sales · benefits pending", status: "running" },
      { id: "3", label: "L. Wong — designer · access provisioning", status: "running" },
      { id: "4", label: "P. Singh — analyst · queued", status: "queued" },
    ],
  ),
  sk("hr", "right-to-work", "Right-to-work check",
    "Run the federal and state checks every employer must run before day one.",
    "verified",
    [
      { label: "Checks completed", value: "1,240", spark: [110, 120, 130, 140, 150, 160, 170] },
      { label: "Pass rate", value: "99.8%", spark: [99, 99, 99, 99, 100, 100, 100] },
    ],
    [
      { id: "1", label: "K. Otieno — passed", status: "done" },
      { id: "2", label: "M. Strauss — exception · escalated", status: "running" },
      { id: "3", label: "L. Wong — passed", status: "done" },
      { id: "4", label: "P. Singh — queued", status: "queued" },
    ],
  ),
  sk("hr", "benefits-enrollment", "Benefits enrollment",
    "Enroll new and changing employees in the right benefits package.",
    "heart",
    [
      { label: "Enrollments processed", value: "880", spark: [80, 90, 100, 110, 120, 130, 140] },
      { label: "Avg time to confirm", value: "1.4 days", spark: [4.0, 3.4, 2.8, 2.2, 1.8, 1.6, 1.4], deltaPct: -65 },
    ],
    [
      { id: "1", label: "K. Otieno — health + 401k confirmed", status: "done" },
      { id: "2", label: "M. Strauss — health enrollment in progress", status: "running" },
      { id: "3", label: "Open enrollment — 312 employees", status: "running" },
      { id: "4", label: "Q3 dental switch — queued", status: "queued" },
    ],
  ),
  sk("hr", "perf-review", "Performance review cycle",
    "Run the performance review cycle from self-review to calibration.",
    "clipboard",
    [
      { label: "Reviews drafted", value: "2,180", spark: [180, 220, 280, 340, 420, 500, 560], deltaPct: 24 },
      { label: "Calibration coverage", value: "100%", spark: [88, 92, 94, 96, 98, 100, 100] },
    ],
    [
      { id: "1", label: "Eng team A — self-reviews complete", status: "done" },
      { id: "2", label: "Sales — manager reviews 70%", status: "running" },
      { id: "3", label: "Calibration sessions scheduled", status: "queued" },
    ],
  ),
  sk("hr", "time-off", "Time-off approval",
    "Approve time-off requests with policy and coverage in mind.",
    "calendar",
    [
      { label: "Requests handled", value: "3,420", spark: [300, 340, 380, 420, 460, 500, 540] },
      { label: "Avg decision", value: "12 min", spark: [180, 120, 80, 50, 30, 18, 12], deltaPct: -93 },
    ],
    [
      { id: "1", label: "K. Otieno — 5 days · approved", status: "done" },
      { id: "2", label: "M. Strauss — 2 weeks · coverage check", status: "running" },
      { id: "3", label: "L. Wong — 1 day · auto-approved", status: "done" },
      { id: "4", label: "P. Singh — 3 days · queued", status: "queued" },
    ],
  ),
  sk("hr", "comp-review", "Compensation review",
    "Run compensation review cycles with market data and equity bands.",
    "scale",
    [
      { label: "Employees reviewed", value: "1,840", spark: [200, 320, 480, 720, 980, 1320, 1840] },
      { label: "Avg merit increase", value: "4.2%", spark: [3.8, 3.9, 4.0, 4.0, 4.1, 4.1, 4.2] },
    ],
    [
      { id: "1", label: "Eng band review — complete", status: "done" },
      { id: "2", label: "Sales band review — running", status: "running" },
      { id: "3", label: "Equity refresh proposals drafted", status: "running" },
      { id: "4", label: "Manager 1:1 prep packets — queued", status: "queued" },
    ],
  ),
  sk("hr", "offboarding", "Offboarding workflow",
    "Wind down departing employees safely, on time, and with dignity.",
    "key",
    [
      { label: "Departures handled", value: "78", spark: [6, 8, 10, 12, 14, 16, 18] },
      { label: "Access revoked < 1 hr", value: "100%", spark: [88, 92, 96, 98, 100, 100, 100] },
    ],
    [
      { id: "1", label: "R. Davies — equipment returned · access revoked", status: "done" },
      { id: "2", label: "T. Hall — final-pay calc · benefits cobra", status: "running" },
      { id: "3", label: "S. Park — exit interview scheduled", status: "queued" },
    ],
  ),
  sk("hr", "reference-check", "Reference check",
    "Run reference checks for new hires before offer extension.",
    "verified",
    [
      { label: "References completed", value: "612", spark: [50, 56, 62, 68, 74, 80, 86] },
      { label: "Avg turnaround", value: "1.8 days", spark: [5.0, 4.0, 3.4, 2.8, 2.4, 2.0, 1.8], deltaPct: -64 },
    ],
    [
      { id: "1", label: "K. Otieno — 3 of 3 received", status: "done" },
      { id: "2", label: "M. Strauss — 2 of 3 · awaiting last", status: "running" },
      { id: "3", label: "L. Wong — outreach sent", status: "running" },
      { id: "4", label: "P. Singh — queued", status: "queued" },
    ],
  ),
  sk("hr", "contract-renewal", "Contract renewal",
    "Renew contractor and fixed-term contracts with the right approvals.",
    "briefcase",
    [
      { label: "Contracts renewed", value: "228", spark: [20, 24, 28, 32, 36, 40, 44] },
      { label: "Avg lead time", value: "14 days", spark: [4, 6, 8, 10, 12, 13, 14] },
    ],
    [
      { id: "1", label: "T. Larsson — renewed · 12 months", status: "done" },
      { id: "2", label: "A. Ramirez — terms negotiation", status: "running" },
      { id: "3", label: "J. Park — manager approval pending", status: "running" },
      { id: "4", label: "M. Davis — queued", status: "queued" },
    ],
  ),
  sk("hr", "training", "Training assignment",
    "Assign required training and chase completion.",
    "clipboard",
    [
      { label: "Modules assigned", value: "5,840", spark: [400, 480, 580, 680, 800, 920, 1080] },
      { label: "Completion rate", value: "97.4%", spark: [86, 90, 92, 94, 96, 97, 97] },
    ],
    [
      { id: "1", label: "Security awareness — Q1 cohort complete", status: "done" },
      { id: "2", label: "Anti-harassment — 88% complete · chasing", status: "running" },
      { id: "3", label: "Manager training — May cohort scheduled", status: "queued" },
    ],
  ),
  sk("hr", "headcount", "Headcount planning",
    "Plan headcount across the company and reconcile with finance.",
    "layers",
    [
      { label: "Roles open", value: "84", spark: [60, 64, 68, 72, 76, 80, 84] },
      { label: "Forecast accuracy", value: "94.2%", spark: [86, 88, 90, 92, 93, 94, 94] },
    ],
    [
      { id: "1", label: "Eng plan — locked", status: "done" },
      { id: "2", label: "Sales plan — finance reconciliation", status: "running" },
      { id: "3", label: "G&A plan — drafted", status: "done" },
      { id: "4", label: "Q3 reforecast — queued", status: "queued" },
    ],
  ),
  sk("hr", "engagement", "Engagement survey",
    "Run pulse and engagement surveys, surface themes, route to managers.",
    "heart",
    [
      { label: "Responses collected", value: "3,840", spark: [300, 360, 420, 500, 580, 660, 740] },
      { label: "Response rate", value: "82%", spark: [62, 66, 70, 74, 78, 80, 82] },
    ],
    [
      { id: "1", label: "Q1 pulse — themes shared with managers", status: "done" },
      { id: "2", label: "Manager dashboards refreshed", status: "running" },
      { id: "3", label: "Q2 pulse — drafting", status: "queued" },
    ],
  ),

  // ───────────────────────────── ERP ─────────────────────────────
  sk("erp", "purchase-order", "Purchase order",
    "Validate, approve, and post purchase orders into the ERP.",
    "clipboard",
    [
      { label: "POs processed", value: "1,840", spark: [160, 180, 200, 220, 250, 280, 310], deltaPct: 14 },
      { label: "Avg cycle", value: "5 days", spark: [14, 12, 10, 8, 7, 6, 5], deltaPct: -64 },
    ],
    [
      { id: "1", label: "PO 3D71FA — VP approval pending · $132K", status: "running" },
      { id: "2", label: "PO 91A2C0 — auto-approved · $4.8K", status: "done" },
      { id: "3", label: "PO 22F11B — director review · $48K", status: "running" },
      { id: "4", label: "PO 7E904D — queued · $9.2K", status: "queued" },
    ],
  ),
  sk("erp", "goods-receipt", "Goods receipt",
    "Match incoming shipments to purchase orders and invoices.",
    "check",
    [
      { label: "Receipts matched", value: "2,310", spark: [180, 220, 260, 300, 340, 380, 420], deltaPct: 12 },
      { label: "3-way match rate", value: "98.4%", spark: [92, 94, 95, 96, 97, 98, 98] },
    ],
    [
      { id: "1", label: "PO 3D71FA — partial receipt · 80% delivered", status: "running" },
      { id: "2", label: "PO 91A2C0 — full receipt matched", status: "done" },
      { id: "3", label: "PO 22F11B — quantity mismatch · investigating", status: "running" },
      { id: "4", label: "PO 7E904D — queued", status: "queued" },
    ],
  ),
  sk("erp", "inventory-recon", "Inventory reconciliation",
    "Reconcile physical inventory counts against the ERP record.",
    "database",
    [
      { label: "SKUs reconciled", value: "62,400", spark: [5000, 5800, 6800, 7800, 8800, 9800, 10800] },
      { label: "Variance value", value: "$84K", spark: [320, 280, 240, 200, 160, 120, 84], deltaPct: -74 },
    ],
    [
      { id: "1", label: "Warehouse SF — 12,400 SKUs reconciled", status: "done" },
      { id: "2", label: "Warehouse NJ — count in progress", status: "running" },
      { id: "3", label: "Warehouse TX — variance investigation", status: "running" },
      { id: "4", label: "Warehouse CA — queued", status: "queued" },
    ],
  ),
  sk("erp", "vendor-contract", "Vendor contract",
    "Track vendor contracts, renewals, and pricing tiers.",
    "briefcase",
    [
      { label: "Contracts active", value: "412", spark: [380, 388, 395, 400, 405, 408, 412] },
      { label: "Renewal lead time", value: "62 days", spark: [22, 30, 40, 48, 54, 58, 62] },
    ],
    [
      { id: "1", label: "Snowflake — auto-renewed · 12 months", status: "done" },
      { id: "2", label: "Datadog — terms negotiation", status: "running" },
      { id: "3", label: "AWS — enterprise discount review", status: "running" },
      { id: "4", label: "Cloudflare — queued", status: "queued" },
    ],
  ),
  sk("erp", "sales-order", "Sales order",
    "Validate and post sales orders, with credit checks and pricing.",
    "send",
    [
      { label: "Orders processed", value: "5,840", spark: [400, 480, 580, 680, 800, 940, 1080], deltaPct: 18 },
      { label: "Order-to-cash", value: "12 days", spark: [22, 20, 18, 16, 14, 13, 12], deltaPct: -45 },
    ],
    [
      { id: "1", label: "SO 47A2 — Acme Studios · auto-approved", status: "done" },
      { id: "2", label: "SO 5102 — Helios Trading · credit hold", status: "running" },
      { id: "3", label: "SO 5311 — Northwind · pricing override pending", status: "running" },
      { id: "4", label: "SO 5604 — queued", status: "queued" },
    ],
  ),
  sk("erp", "demand-forecast", "Demand forecast",
    "Forecast demand and feed it back into procurement and production.",
    "scale",
    [
      { label: "SKUs forecasted", value: "12,200", spark: [9000, 9800, 10400, 10800, 11200, 11600, 12200] },
      { label: "Forecast accuracy", value: "92.4%", spark: [82, 84, 86, 88, 90, 91, 92] },
    ],
    [
      { id: "1", label: "Q2 SKU plan — published", status: "done" },
      { id: "2", label: "Long-tail SKU re-forecast — running", status: "running" },
      { id: "3", label: "Holiday season pre-build — queued", status: "queued" },
    ],
  ),
  sk("erp", "production-schedule", "Production schedule",
    "Schedule production runs against capacity and material availability.",
    "calendar",
    [
      { label: "Lines scheduled", value: "184", spark: [16, 18, 20, 22, 24, 26, 28] },
      { label: "On-time rate", value: "96.4%", spark: [86, 88, 90, 92, 94, 95, 96] },
    ],
    [
      { id: "1", label: "Line A — week 18 schedule locked", status: "done" },
      { id: "2", label: "Line B — material delay · re-sequencing", status: "running" },
      { id: "3", label: "Line C — week 19 draft", status: "running" },
      { id: "4", label: "Line D — queued", status: "queued" },
    ],
  ),
  sk("erp", "quality-inspection", "Quality inspection",
    "Run incoming and in-line quality inspections and route failures.",
    "shield",
    [
      { label: "Lots inspected", value: "1,140", spark: [80, 90, 100, 110, 120, 130, 140] },
      { label: "Pass rate", value: "98.8%", spark: [94, 95, 96, 97, 98, 98, 99] },
    ],
    [
      { id: "1", label: "Lot 4421 — incoming · passed", status: "done" },
      { id: "2", label: "Lot 4488 — in-line · investigating", status: "running" },
      { id: "3", label: "Lot 4502 — vendor return drafted", status: "running" },
      { id: "4", label: "Lot 4517 — queued", status: "queued" },
    ],
  ),
  sk("erp", "shipping-dispatch", "Shipping dispatch",
    "Dispatch outbound shipments and confirm carrier handover.",
    "send",
    [
      { label: "Shipments dispatched", value: "8,420", spark: [600, 720, 840, 960, 1080, 1200, 1320] },
      { label: "On-time pickup", value: "99.1%", spark: [94, 96, 97, 98, 98, 99, 99] },
    ],
    [
      { id: "1", label: "Wave 18 — UPS pickup confirmed", status: "done" },
      { id: "2", label: "Wave 19 — FedEx late · re-routing", status: "running" },
      { id: "3", label: "Wave 20 — building", status: "running" },
      { id: "4", label: "Wave 21 — queued", status: "queued" },
    ],
  ),
  sk("erp", "returns", "Returns processing",
    "Receive, inspect, and credit customer returns.",
    "route",
    [
      { label: "Returns processed", value: "1,420", spark: [100, 120, 140, 160, 180, 200, 220] },
      { label: "Avg credit time", value: "2.4 days", spark: [7, 6, 5, 4, 3.4, 2.8, 2.4], deltaPct: -66 },
    ],
    [
      { id: "1", label: "RMA 88A1 — restock · credit issued", status: "done" },
      { id: "2", label: "RMA 88B2 — inspection · partial credit", status: "running" },
      { id: "3", label: "RMA 88C9 — vendor warranty claim", status: "running" },
      { id: "4", label: "RMA 88D4 — queued", status: "queued" },
    ],
  ),
  sk("erp", "master-data", "Master-data sync",
    "Keep vendor, customer, and product records consistent across systems.",
    "database",
    [
      { label: "Records synced", value: "184,000", spark: [12000, 16000, 20000, 24000, 28000, 32000, 36000] },
      { label: "Conflict rate", value: "0.2%", spark: [1.4, 1.0, 0.8, 0.6, 0.4, 0.3, 0.2], deltaPct: -86 },
    ],
    [
      { id: "1", label: "Vendor master — 412 updates pushed", status: "done" },
      { id: "2", label: "Product master — 28 conflicts adjudicating", status: "running" },
      { id: "3", label: "Customer master — incremental sync", status: "running" },
      { id: "4", label: "Pricelist sync — queued", status: "queued" },
    ],
  ),
  sk("erp", "pricing-update", "Pricing update",
    "Roll out price changes across regions, currencies, and customer tiers.",
    "tag",
    [
      { label: "Lines updated", value: "9,840", spark: [800, 900, 1000, 1100, 1200, 1300, 1400], deltaPct: 16 },
      { label: "Approval cycle", value: "1.2 days", spark: [4, 3.4, 2.8, 2.2, 1.8, 1.4, 1.2], deltaPct: -70 },
    ],
    [
      { id: "1", label: "EU price increase 4% — published", status: "done" },
      { id: "2", label: "APAC tier review — pending VP approval", status: "running" },
      { id: "3", label: "Volume discount refresh — running", status: "running" },
      { id: "4", label: "Promo calendar update — queued", status: "queued" },
    ],
  ),
];

export function getSubSkill(id: string): SubSkill | undefined {
  return subSkills.find((s) => s.id === id);
}

export function listSubSkillsByParent(parent: SkillSlug): SubSkill[] {
  return subSkills.filter((s) => s.parent === parent);
}
